on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*-*-*-*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{runner.workspace}}/Qt
          key: ${{ runner.os }}-qttools-${{ hashFiles('**/reset-caches.txt') }}
    
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.9.1'
          dir: ${{runner.workspace}}/Qt
          setup-python: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build RCC Files
        run: |
          pwd
          qmake -v
          mkdir src/build
          python ./ci_scripts/build_resources.py

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAGNAME::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Custom Icon Themes (${{ steps.get_tag_name.outputs.TAGNAME }})
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
          artifacts: './src/build/*.rcc'
